import wandb
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ==========================================
# 1. Configuration
# ==========================================
ENTITY  = "michalowski-jb-tilburg-university"
PROJECT = "HyperFisher"

NUM_TASKS = 20

# ==========================================
# 2. Fetch Data & Calculate CL Metrics
# ==========================================
api = wandb.Api()

print(f"Fetching runs from {ENTITY}/{PROJECT}...")
runs = api.runs(f"{ENTITY}/{PROJECT}", filters={
    "$or": [
        {"config.experiment_id": 414},
        {"config.experiment_id": 415},
        {"config.experiment_id": "414"},
        {"config.experiment_id": "415"}
    ]
})

data = []

for run in runs:
    exp_id = str(run.config.get("experiment_id"))
    seed = str(run.config.get("seed", "unknown"))
    
    acc_type = "EMA" if exp_id == "414" else "MAX"
    method_name = "eFOPNG (EMA)" if exp_id == "414" else "eFOPNG (MAX)"
    
    print(f"Processing Exp {exp_id} | Seed {seed} | {method_name}...")
    
    # Extract the nested accuracy dictionary from run.summary
    acc_dict = None
    possible_keys = ["best/results", "efopng_ema/results", "efopng/results"]
    for key in possible_keys:
        if key in run.summary:
            res_obj = run.summary[key]
            if "acc" in res_obj:
                acc_dict = res_obj["acc"]
                break
                
    if acc_dict is None:
        print(f"  -> Skipping seed {seed}: Could not find nested 'acc' dictionary in summary.")
        continue

    # Build R_matrix
    R_matrix = []
    for t in range(1, NUM_TASKS + 1):
        if str(t) not in acc_dict:
            print(f"  -> Missing task {t} in 'acc' dictionary. Skipping.")
            break
        R_matrix.append(acc_dict[str(t)])
        
    if len(R_matrix) != NUM_TASKS:
        continue
        
    # Calculate Trajectory Avg Accuracy and BWT at each step
    for step_idx in range(NUM_TASKS):
        current_step = step_idx + 1          
        current_evals = R_matrix[step_idx]   
        
        # Average Accuracy
        seen_accs = current_evals[:current_step]
        avg_acc = sum(seen_accs) / current_step
        
        # BWT
        if current_step == 1:
            bwt = 0.0
        else:
            bwt_sum = sum(current_evals[i] - R_matrix[i][i] for i in range(current_step - 1))
            bwt = bwt_sum / (current_step - 1)
            
        data.append({
            "Seed": seed,
            "Accumulation Type": method_name,
            "Task": current_step,
            "Accuracy": avg_acc,
            "BWT": bwt
        })

df = pd.DataFrame(data)

if df.empty:
    print("No data found! Check your W&B entity/project.")
    exit()

# ==========================================
# 3. Plotting
# ==========================================
sns.set_theme(style="whitegrid", context="paper", font_scale=1.2)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Define colors to keep EMA and MAX consistent between seeds and averages
palette = {"eFOPNG (EMA)": "tab:blue", "eFOPNG (MAX)": "tab:orange"}

# ----------------------------------------------------
# Plot 1: Trajectory Accuracy
# ----------------------------------------------------
# 1A. Plot individual seeds (thin, transparent lines, no legend)
sns.lineplot(
    data=df, x="Task", y="Accuracy", 
    hue="Accumulation Type", units="Seed", estimator=None,
    palette=palette, alpha=0.3, linewidth=1, ax=axes[0], legend=False
)
# 1B. Plot Mean Average (thick line with markers)
sns.lineplot(
    data=df, x="Task", y="Accuracy", 
    hue="Accumulation Type", estimator="mean", errorbar=None,
    palette=palette, linewidth=3, markersize=8, ax=axes[0]
)

axes[0].set_title("Trajectory Average Accuracy\n(Thin = Seeds, Thick = Average)")
axes[0].set_xlabel("Tasks Learned")
axes[0].set_ylabel("Average Accuracy (Seen Tasks)")
axes[0].set_xticks(range(1, NUM_TASKS + 1))

# ----------------------------------------------------
# Plot 2: Backward Transfer (BWT)
# ----------------------------------------------------
# 2A. Plot individual seeds (thin, transparent lines, no legend)
sns.lineplot(
    data=df, x="Task", y="BWT", 
    hue="Accumulation Type", units="Seed", estimator=None,
    palette=palette, alpha=0.3, linewidth=1, ax=axes[1], legend=False
)
# 2B. Plot Mean Average (thick line with markers)
sns.lineplot(
    data=df, x="Task", y="BWT", 
    hue="Accumulation Type", estimator="mean", errorbar=None,
    palette=palette, linewidth=3, markersize=8, ax=axes[1]
)

axes[1].set_title("Trajectory Backward Transfer (BWT)\n(Thin = Seeds, Thick = Average)")
axes[1].set_xlabel("Tasks Learned")
axes[1].set_ylabel("BWT")
axes[1].set_xticks(range(1, NUM_TASKS + 1))

# Clean up duplicate legends generated by seaborn
handles, labels = axes[0].get_legend_handles_labels()
axes[0].legend(handles=handles, labels=labels, loc='lower left', fontsize=10)
axes[1].legend(handles=handles, labels=labels, loc='lower left', fontsize=10)

plt.suptitle("Config 14 & 15: EMA vs MAX Fisher Accumulation (Averaged Across Seeds)", y=1.05, fontsize=16)
plt.tight_layout()

# Save and Show
output_file = "visualizations/EMA_vs_MAX_F_old_accumulation.png"
plt.savefig(output_file, dpi=300, bbox_inches="tight")
print(f"Plot saved successfully as '{output_file}'!")
plt.show()