"""
hypernet_fopng_cifar10.py
=========================
Self-contained FOPNG (Fisher-Orthogonal Projected Natural Gradient)
for a chunked HyperNetwork on Split CIFAR-10.

Architecture
------------
  HyperNetwork
  ├── task_emb   : nn.Embedding(num_tasks, task_emb_dim)   — task-specific
  ├── chunk_emb  : nn.Embedding(num_chunks, chunk_emb_dim) — shared
  └── layers     : MLP(task_emb_dim+chunk_emb_dim → chunk_size) — shared
                   generates weights for ↓
  TargetCNN  (frozen template, weights generated by HyperNetwork)
  └── conv1→conv2→conv3→fc1→fc2

FOPNG applies to shared_params = {layers, chunk_emb}.
Task embeddings are updated with a plain Adam step (no projection)
because each row belongs to exactly one task and cannot cause cross-task
interference.

FOPNG-PF variant is used: collected gradient directions are pre-multiplied
by the task's Fisher diagonal before storing them in memory, which
simplifies the projection formula.

Split CIFAR-10: 5 tasks, 2 classes each ([[0,1],[2,3],[4,5],[6,7],[8,9]])
"""

# ─────────────────────────────────────────────────────────────────────────────
# Imports
# ─────────────────────────────────────────────────────────────────────────────
import random
from dataclasses import dataclass
from math import ceil
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.func import functional_call
from torch.utils.data import DataLoader, Dataset
from torchvision import datasets, transforms
from tqdm import tqdm


# ─────────────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Config:
    seed: int = 42
    device: str = "auto"

    # ── Training ──────────────────────────────────────────────
    batch_size: int = 64
    epochs_per_task: int = 10
    lr: float = 1e-3           # Shared-param lr (also Adam lr for task 0)
    task_emb_lr: float = 0.05  # Task-embedding Adam lr

    # ── FOPNG ─────────────────────────────────────────────────
    grads_per_task: int = 150   # Fisher-preconditioned gradient directions to collect after each task
    max_directions: int = 750   # Upper bound on total stored directions
    fopng_lambda_reg: float = 1e-3       # Tikhonov regularisation λ
    fopng_new_fisher_weight: float = 0.5 # EMA weight for F_old update
    fisher_batch_size: Optional[int] = 512  # Samples for Fisher estimation (None = full train set)

    # ── HyperNetwork ──────────────────────────────────────────
    num_tasks: int = 5
    task_embedding_dim: int = 16
    chunk_size: int = 256
    chunk_embedding_dim: int = 8
    hyper_hidden_dim: int = 64

    def __post_init__(self):
        if self.device == "auto":
            if torch.cuda.is_available():
                self.device = "cuda"
            elif torch.backends.mps.is_available():
                self.device = "mps"
            else:
                self.device = "cpu"


# ─────────────────────────────────────────────────────────────────────────────
# Dataset  ── Split CIFAR-10
# ─────────────────────────────────────────────────────────────────────────────

CIFAR10_MEAN = (0.4914, 0.4822, 0.4465)
CIFAR10_STD  = (0.2470, 0.2435, 0.2616)
CLASS_GROUPS = [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]


class SubsetByClass(Dataset):
    """Keep only samples whose labels are in `allowed_classes`, remapped to 0…k-1."""

    def __init__(self, base_dataset, allowed_classes: List[int]):
        self.base = base_dataset
        self.class_to_new = {c: i for i, c in enumerate(sorted(allowed_classes))}
        self.indices = [
            i for i, (_, lbl) in enumerate(base_dataset)
            if int(lbl) in self.class_to_new
        ]

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):
        img, lbl = self.base[self.indices[idx]]
        return img, self.class_to_new[int(lbl)]


def build_split_cifar10(
    batch_size: int = 64,
    root: str = "./data"
) -> Tuple[List[Tuple[DataLoader, DataLoader]], List[List[int]]]:
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(CIFAR10_MEAN, CIFAR10_STD),
    ])
    base_train = datasets.CIFAR10(root, train=True,  download=True, transform=transform)
    base_test  = datasets.CIFAR10(root, train=False, download=True, transform=transform)

    tasks = []
    for grp in CLASS_GROUPS:
        tr = DataLoader(SubsetByClass(base_train, grp), batch_size=batch_size, shuffle=True,  num_workers=2, pin_memory=True)
        te = DataLoader(SubsetByClass(base_test,  grp), batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)
        tasks.append((tr, te))
    return tasks, CLASS_GROUPS


# ─────────────────────────────────────────────────────────────────────────────
# Target Network  ── small CNN, weights are *generated* by the HyperNetwork
# ─────────────────────────────────────────────────────────────────────────────

class TargetCNN(nn.Module):
    """
    Tiny CNN used as the *template* for the HyperNetwork.
    All parameters are overwritten at inference time via functional_call.

    Input : 3 × 32 × 32
    After conv1 + pool  →  16 × 16 × 16
    After conv2 + pool  →  32 ×  8 ×  8
    After conv3 + pool  →  32 ×  4 ×  4   (512 features)
    FC1  →  64
    FC2  →  num_classes (2 per task)

    Total parameters: ~47 300
    With chunk_size=256 → 185 chunks
    """

    def __init__(self, num_classes: int = 2):
        super().__init__()
        self.conv1 = nn.Conv2d(3,  16, 3, padding=1)
        self.conv2 = nn.Conv2d(16, 32, 3, padding=1)
        self.conv3 = nn.Conv2d(32, 32, 3, padding=1)
        self.fc1   = nn.Linear(32 * 4 * 4, 64)
        self.fc2   = nn.Linear(64, num_classes)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = F.relu(F.max_pool2d(self.conv1(x), 2))   # 16 × 16
        x = F.relu(F.max_pool2d(self.conv2(x), 2))   #  8 ×  8
        x = F.relu(F.max_pool2d(self.conv3(x), 2))   #  4 ×  4
        x = x.view(x.size(0), -1)                    # 512
        x = F.relu(self.fc1(x))                       #  64
        return self.fc2(x)                            #   2


# ─────────────────────────────────────────────────────────────────────────────
# HyperNetwork
# ─────────────────────────────────────────────────────────────────────────────

class HyperNetwork(nn.Module):
    """
    Chunked HyperNetwork that generates all weights of `target_template`.

    spawn(task_id) → computes self.target_params from the generator MLP.
    forward(x)    → runs functional_call(target_network, target_params, x).

    shared_params property: layers + chunk_emb  (used by FOPNG)
    task_emb is excluded because row t only affects task t's output.
    """

    def __init__(self, config: Config, target_template: nn.Module, device: torch.device):
        super().__init__()
        self.device = device

        # ── Frozen target template ────────────────────────────────────────
        self.target_network = target_template.to(device)
        for p in self.target_network.parameters():
            p.requires_grad = False

        self.num_target_params = sum(p.numel() for p in self.target_network.parameters())
        print(f"[HyperNetwork] Target params : {self.num_target_params:,}")

        # ── Chunking ──────────────────────────────────────────────────────
        self.chunk_size = config.chunk_size
        self.num_chunks = ceil(self.num_target_params / self.chunk_size)
        self.chunk_emb  = nn.Embedding(self.num_chunks, config.chunk_embedding_dim).to(device)

        # ── Task embeddings ───────────────────────────────────────────────
        self.task_emb = nn.Embedding(config.num_tasks, config.task_embedding_dim).to(device)

        # ── Generator MLP ─────────────────────────────────────────────────
        in_dim = config.task_embedding_dim + config.chunk_embedding_dim
        h      = config.hyper_hidden_dim
        self.layers = nn.Sequential(
            nn.Linear(in_dim, h), nn.LeakyReLU(0.1),
            nn.Linear(h,    h*2), nn.LeakyReLU(0.1),
            nn.Linear(h*2, config.chunk_size),
        ).to(device)

        # Prevent variance explosion on the large output layer
        with torch.no_grad():
            nn.init.normal_(self.layers[-1].weight, 0.0, 0.05)
            nn.init.normal_(self.layers[-1].bias,   0.0, 0.01)

        n_gen   = sum(p.numel() for p in self.layers.parameters())
        n_cemb  = self.chunk_emb.weight.numel()
        n_temb  = self.task_emb.weight.numel()
        n_shared = n_gen + n_cemb
        print(f"[HyperNetwork] Generator MLP : {n_gen:,}")
        print(f"[HyperNetwork] Chunk emb     : {n_cemb:,}  ({self.num_chunks} chunks × {config.chunk_embedding_dim})")
        print(f"[HyperNetwork] Task  emb     : {n_temb:,}  ({config.num_tasks} tasks × {config.task_embedding_dim})")
        print(f"[HyperNetwork] Shared params : {n_shared:,}  ← FOPNG acts on these")

        self.target_params: Optional[Dict[str, torch.Tensor]] = None

    # ── Core methods ──────────────────────────────────────────────────────────

    def spawn(self, task_id: int) -> None:
        """
        Generate target-network weights for `task_id`.
        Must be called before every forward pass.
        Gradients flow back through this into layers and chunk_emb.
        """
        t_emb = self.task_emb(torch.tensor(task_id, device=self.device)).view(-1)  # [emb_dim]
        t_vec = t_emb.unsqueeze(0).expand(self.num_chunks, -1)                      # [C, emb_dim]

        chunk_ids = torch.arange(self.num_chunks, device=self.device)
        c_vec = self.chunk_emb(chunk_ids)                                            # [C, chunk_emb_dim]

        x      = torch.cat([t_vec, c_vec], dim=1)                                   # [C, in_dim]
        flat_w = self.layers(x).reshape(-1)[:self.num_target_params]                 # trim padding

        self.target_params = self._to_param_dict(flat_w)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        assert self.target_params is not None, "Call spawn(task_id) before forward()."
        return functional_call(self.target_network, self.target_params, x)

    def _to_param_dict(self, flat: torch.Tensor) -> Dict[str, torch.Tensor]:
        out, ptr = {}, 0
        for name, p in self.target_network.named_parameters():
            n = p.numel()
            out[name] = flat[ptr : ptr + n].view_as(p)
            ptr += n
        return out

    # ── Param groupings ───────────────────────────────────────────────────────

    @property
    def shared_params(self) -> List[nn.Parameter]:
        """
        Parameters shared across ALL tasks.
        Excludes task_emb: each row is owned by exactly one task,
        so task-emb gradients carry zero cross-task interference signal
        and should not be projected.
        """
        return list(self.layers.parameters()) + [self.chunk_emb.weight]

    @property
    def num_shared_params(self) -> int:
        return sum(p.numel() for p in self.shared_params)


# ─────────────────────────────────────────────────────────────────────────────
# Gradient utilities  (operate on explicit parameter lists, not model.parameters())
# ─────────────────────────────────────────────────────────────────────────────

def get_grad_vector(params: List[nn.Parameter]) -> torch.Tensor:
    """Concatenate gradients of `params` into a single 1-D tensor."""
    grads = []
    for p in params:
        if p.grad is None:
            grads.append(torch.zeros(p.numel(), device=p.device))
        else:
            grads.append(p.grad.detach().view(-1))
    return torch.cat(grads)


def apply_update(params: List[nn.Parameter], delta: torch.Tensor) -> None:
    """Add `delta` (1-D) in-place to the parameters in `params`."""
    idx = 0
    with torch.no_grad():
        for p in params:
            n = p.numel()
            p.add_(delta[idx : idx + n].view_as(p))
            idx += n


def zero_grad(params: List[nn.Parameter]) -> None:
    for p in params:
        if p.grad is not None:
            p.grad.zero_()


# ─────────────────────────────────────────────────────────────────────────────
# Fisher estimation  ── diagonal, over shared params only
# ─────────────────────────────────────────────────────────────────────────────

def estimate_diagonal_fisher(
    hyper_net: HyperNetwork,
    task_id: int,
    dataloader: DataLoader,
    device: str,
    max_samples: Optional[int] = None,
) -> torch.Tensor:
    """
    Empirical diagonal Fisher over *shared* parameters for `task_id`.

    F_ii = (1/N) Σ_n  (∂ L_n / ∂ θ_i)²

    Returns a 1-D tensor of shape [num_shared_params].
    """
    shared = hyper_net.shared_params
    fisher  = torch.zeros(hyper_net.num_shared_params, device=device)
    n_seen  = 0
    criterion = nn.CrossEntropyLoss()

    hyper_net.eval()
    for x, y in tqdm(dataloader, desc=f"  Fisher task {task_id}", leave=False):
        if max_samples and n_seen >= max_samples:
            break
        x, y = x.to(device), y.to(device)

        for i in range(x.size(0)):
            if max_samples and n_seen >= max_samples:
                break
            hyper_net.zero_grad()
            hyper_net.spawn(task_id)
            loss = criterion(hyper_net(x[i : i + 1]), y[i : i + 1])
            loss.backward()

            g      = get_grad_vector(shared)   # [D_shared]
            fisher += g * g
            n_seen += 1

    hyper_net.train()
    return fisher / max(n_seen, 1)


# ─────────────────────────────────────────────────────────────────────────────
# Gradient memory  ── stores Fisher-preconditioned directions
# ─────────────────────────────────────────────────────────────────────────────

class GradientMemory:
    """Raw storage for Fisher-preconditioned gradient directions with SVD compression."""

    def __init__(self, max_dirs: int = 500):
        self.max_dirs = max_dirs
        # Keep current task's gradients in a list for O(1) appending
        self.vectors: List[torch.Tensor] = []
        # Store the compressed basis from previous tasks here
        self.matrix: Optional[torch.Tensor] = None

    def add(self, v: torch.Tensor) -> None:
        """Fast append to list (no heavy computation here)."""
        self.vectors.append(v.clone().detach())

    def compress(self) -> None:
        """Perform SVD compression ONCE after a task's collection is finished."""
        if not self.vectors:
            return

        # 1. Stack new 1D vectors into a 2D matrix [D, K_new]
        new_G = torch.stack(self.vectors, dim=1)
        
        # 2. Combine with the existing compressed basis if it exists
        if self.matrix is not None:
            # Concatenate along the column dimension: [D, K_old] and [D, K_new]
            # Result: [D, K_old + K_new]
            G = torch.cat([self.matrix, new_G], dim=1)
        else:
            G = new_G
        
        # 3. Perform SVD if we exceed the budget
        if G.size(1) > self.max_dirs:
            # Move to GPU if available to speed up SVD calculation
            device = G.device
            print(f" [FOPNG] Compressing G: {G.size(1)} -> {self.max_dirs} directions...")
            
            U, _, _ = torch.linalg.svd(G, full_matrices=False)
            # Retain only the top singular vectors as the new basis
            self.matrix = U[:, :self.max_dirs]
        else:
            self.matrix = G
            
        # 4. Clear the temporary list to free memory
        self.vectors = []

    def get_matrix(self) -> Optional[torch.Tensor]:
        """Returns [D_shared, K] matrix of stored directions."""
        return self.matrix

    def clear(self) -> None:
        self.vectors = []
        self.matrix = None

    def __len__(self) -> int:
        """Returns total number of directions (compressed + pending)."""
        count = len(self.vectors)
        if self.matrix is not None:
            count += self.matrix.size(1)
        return count


def collect_fisher_preconditioned_gradients(
    hyper_net: HyperNetwork,
    task_id: int,
    dataloader: DataLoader,
    memory: GradientMemory,
    num_directions: int,
    fisher: torch.Tensor,
    device: str,
) -> None:
    """
    Collect `num_directions` gradient vectors from task `task_id`, each
    pre-multiplied by the task's Fisher diagonal:

        stored_g = F_task ⊙ g_raw

    This implements the FOPNG-PF scheme.  Using AVE (average-logit) loss
    as the scalar objective for each sample.
    """
    shared    = hyper_net.shared_params
    collected = 0

    hyper_net.eval()
    for x, y in tqdm(dataloader, desc=f"  Collecting grads task {task_id}", leave=False):
        if collected >= num_directions:
            break
        x, y = x.to(device), y.to(device)

        for i in range(x.size(0)):
            if collected >= num_directions:
                break
            hyper_net.zero_grad()
            hyper_net.spawn(task_id)
            logits = hyper_net(x[i : i + 1])
            logits.mean().backward()   # AVE collector: gradient of mean logit

            g_raw = get_grad_vector(shared)   # [D_shared]
            g_pf  = fisher * g_raw            # Fisher pre-multiply
            memory.add(g_pf)
            collected += 1
    memory.compress()
    hyper_net.train()
    print(f"  Collected {collected} directions (memory total: {len(memory)})")


# ─────────────────────────────────────────────────────────────────────────────
# FOPNG-PF update
# ─────────────────────────────────────────────────────────────────────────────

def fopng_prepare(
    F_new: torch.Tensor,  # [D_shared]  diagonal Fisher for current task
    G_pf:  torch.Tensor,  # [D_shared, K]  stored Fisher-preconditioned directions
    lam:   float,
    device: str,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Precompute  A = G_pf^T F_new^{-1} G_pf + λ I  and its pseudo-inverse.

    Called once per epoch (Fisher is re-estimated at the start of each epoch
    in the continual setting), returns (A_inv, A).
    """
    F_new_inv = 1.0 / (F_new + lam)                       # [D_shared]
    scaled_G  = F_new_inv.unsqueeze(1) * G_pf              # [D_shared, K]
    A  = G_pf.T @ scaled_G + lam * torch.eye(G_pf.size(1), device=device)   # [K, K]
    A_inv = torch.linalg.pinv(A)                           # [K, K]
    print(A)
    return A_inv, A


def fopng_compute_update(
    g:     torch.Tensor,  # [D_shared]  current gradient
    F_new: torch.Tensor,  # [D_shared]  diagonal Fisher
    G_pf:  torch.Tensor,  # [D_shared, K]
    A_inv: torch.Tensor,  # [K, K]
    lam:   float,
    lr:    float,
    F_old
) -> torch.Tensor:
    """
    FOPNG-PF update step.

    1. Project g away from the span of G_pf:
           correction = G_pf (A^{-1} G_pf^T g)
           P_g        = g - correction

    2. Natural-gradient step in the F_new metric:
           v* = -lr · F_new^{-1} P_g / √(P_g^T F_new^{-1} P_g)

    Returns the parameter update v* ∈ R^{D_shared}.
    """
    F_new_inv = 1.0 / (F_new + lam)

    # Projection
    G_T_g      = G_pf.T @ g                     # [K]
    correction = (G_pf @ (A_inv @ G_T_g)).view(-1)  # [D_shared]
    P_g        = g - correction                 # [D_shared]

    # Natural-gradient normalised step
    F_inv_P_g = F_new_inv * P_g                 # [D_shared]
    denom     = torch.sqrt((P_g * F_inv_P_g).sum() + 1e-8)
    v_star    = -lr * F_inv_P_g / denom
        # ── 2. Metrics ───────────────────────────────────────────────────────
    # 3. Metrics Calculation
    # Raw Rho: Simple ratio of Euclidean norms
    raw_rho = (P_g.norm() / (g.norm() + 1e-8)).item()
    
    # Weighted Rho: Ratio of norms in the F_old metric
    if F_old is not None:
        # We use the sqrt of F_old to apply it as a weight to the vector elements
        # ||x||_F = sqrt(x^T F x) = sqrt(sum(F_i * x_i^2))
        f_weight = F_old.clamp(min=0).sqrt()
        w_norm_Pg = (f_weight * P_g).norm()
        w_norm_g  = (f_weight * g).norm()
        weighted_rho = (w_norm_Pg / (w_norm_g + 1e-8)).item()
    else:
        weighted_rho = 1.0

    return v_star, weighted_rho, raw_rho


# ─────────────────────────────────────────────────────────────────────────────
# Evaluation
# ─────────────────────────────────────────────────────────────────────────────

@torch.no_grad()
def evaluate(
    hyper_net:  HyperNetwork,
    task_id:    int,
    dataloader: DataLoader,
    device:     str,
) -> Tuple[float, float]:
    """Returns (avg_loss, accuracy) for `task_id`."""
    hyper_net.eval()
    criterion  = nn.CrossEntropyLoss()
    total_loss = total_correct = total_n = 0

    for x, y in dataloader:
        x, y = x.to(device), y.to(device)
        hyper_net.spawn(task_id)
        logits = hyper_net(x)

        total_loss    += criterion(logits, y).item() * x.size(0)
        total_correct += (logits.argmax(1) == y).sum().item()
        total_n       += x.size(0)

    hyper_net.train()
    return total_loss / total_n, total_correct / total_n


# ─────────────────────────────────────────────────────────────────────────────
# Training
# ─────────────────────────────────────────────────────────────────────────────

def run_experiment(config: Config) -> Dict[int, List[float]]:
    """
    Run Split CIFAR-10 continual learning with FOPNG on a HyperNetwork.

    Returns a dict  task_id → [accuracy after task 0, after task 1, …]
    """
    # ── Reproducibility ───────────────────────────────────────────────────
    random.seed(config.seed)
    np.random.seed(config.seed)
    torch.manual_seed(config.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(config.seed)

    device = config.device
    print(f"\nDevice : {device}")

    # ── Data ──────────────────────────────────────────────────────────────
    tasks, class_groups = build_split_cifar10(config.batch_size)
    print(f"Tasks  : {class_groups}")

    # ── Model ─────────────────────────────────────────────────────────────
    target_template = TargetCNN(num_classes=2)
    hyper_net = HyperNetwork(config, target_template, device).to(device)

    # ── Optimisers ────────────────────────────────────────────────────────
    # Shared-param optimizer — used on task 0 and as fallback
    shared_opt = torch.optim.Adam(hyper_net.shared_params, lr=config.lr)
    # Task-embedding optimizer — always used (separate from FOPNG)
    task_emb_opt = torch.optim.SGD([hyper_net.task_emb.weight], lr=config.task_emb_lr)

    criterion = nn.CrossEntropyLoss()

    # ── FOPNG state ───────────────────────────────────────────────────────
    memory  = GradientMemory(max_dirs=config.max_directions)
    F_old:  Optional[torch.Tensor] = None   # running EMA of past Fishers
    # A_inv and G_pf are recomputed each epoch when FOPNG is active
    A_inv:  Optional[torch.Tensor] = None
    G_pf:   Optional[torch.Tensor] = None

    # ── Results ───────────────────────────────────────────────────────────
    results: Dict[int, List[float]] = {t: [] for t in range(config.num_tasks)}

    # ═════════════════════════════════════════════════════════════════════
    for task_id in range(config.num_tasks):
        train_loader, test_loader = tasks[task_id]
        print(f"\n{'='*60}")
        print(f"Task {task_id}  —  classes {class_groups[task_id]}")
        print(f"{'='*60}")
        w_rho = 0
        raw_rho = 0

        # ── Decide whether to use FOPNG this task ─────────────────────
        G_pf = memory.get_matrix()  # None for task 0
        use_fopng = (task_id > 0) and (G_pf is not None) and (F_old is not None)

        if use_fopng:
            print(f"FOPNG active  |  {G_pf.size(1)} stored directions")

        # ── Training epochs ───────────────────────────────────────────
        for epoch in range(config.epochs_per_task):

            # Re-estimate F_new at the start of each FOPNG epoch so that
            # the natural-gradient metric stays current.
            if use_fopng:
                F_new = estimate_diagonal_fisher(
                    hyper_net, task_id, train_loader, device,
                    max_samples=config.fisher_batch_size
                )
                A_inv, _ = fopng_prepare(F_new, G_pf, config.fopng_lambda_reg, device)
            else:
                F_new = None

            hyper_net.train()
            total_loss = total_correct = total_n = 0
            pbar = tqdm(
                train_loader,
                desc=f"  Epoch {epoch+1:2d}/{config.epochs_per_task}",
                leave=False
            )
            batch_n = 0
            for x, y in pbar:
                x, y = x.to(device), y.to(device)

                # ── Forward ───────────────────────────────────────────
                hyper_net.zero_grad()
                hyper_net.spawn(task_id)
                logits = hyper_net(x)
                loss   = criterion(logits, y)
                loss.backward()

                # ── Shared-param update ───────────────────────────────
                if use_fopng:
                    # FOPNG-PF projected natural-gradient step
                    g   = get_grad_vector(hyper_net.shared_params)
                    upd, _w_rho, _raw_rho = fopng_compute_update(
                        g, F_new, G_pf, A_inv,
                        config.fopng_lambda_reg, config.lr, F_old
                    )
                    w_rho += _w_rho
                    raw_rho += _raw_rho
                    apply_update(hyper_net.shared_params, upd)
                    zero_grad(hyper_net.shared_params)   # prevent optimizer touching them
                else:
                    # Plain Adam for task 0 (and if memory is still empty)
                    shared_opt.step()

                # ── Task-embedding update (always plain Adam) ─────────
                # Gradient already set by loss.backward(); only the
                # current task's row is non-zero.
                task_emb_opt.step()

                # ── Bookkeeping ───────────────────────────────────────
                total_loss    += loss.item() * x.size(0)
                total_correct += (logits.argmax(1) == y).sum().item()
                total_n       += x.size(0)
                batch_n += 1
                pbar.set_postfix(
                    loss=f"{total_loss / total_n:.3f}",
                    acc=f"{100 * total_correct / total_n:.1f}%"
                )
            w_rho /= batch_n
            raw_rho /= batch_n
            avg_loss = total_loss / total_n
            avg_acc  = total_correct / total_n
            print(
                f"  Epoch {epoch+1:2d}/{config.epochs_per_task}"
                f"  loss={avg_loss:.4f}  acc={100*avg_acc:.2f}%"
                f"  w_rho={w_rho:.4f}   raw_rho={raw_rho:.4f}"
            )

        # ── Evaluate all tasks ────────────────────────────────────────
        print("\n  Evaluation:")
        for eval_t in range(config.num_tasks):
            _, eval_ldr = tasks[eval_t]
            _, acc = evaluate(hyper_net, eval_t, eval_ldr, device)
            results[eval_t].append(acc)
            marker = " ←" if eval_t == task_id else ""
            print(f"    Task {eval_t} (classes {class_groups[eval_t]}): "
                  f"{100*acc:.2f}%{marker}")

        # ── Post-task: Fisher + gradient collection ───────────────────
        print(f"\n  Post-task processing (task {task_id}) …")

        F_current = estimate_diagonal_fisher(
            hyper_net, task_id, train_loader, device,
            max_samples=config.fisher_batch_size
        )

        # Update running F_old (EMA)
        if F_old is None:
            F_old = F_current.clone()
        else:
            # Arithmetic Mean: All tasks have exactly 1/N weight BIG CHANGE
            n = task_id+1
            F_old = ((n - 1) / n) * F_old + (1.0 / n) * F_current.clone()

        # Collect Fisher-preconditioned gradient directions into memory
        collect_fisher_preconditioned_gradients(
            hyper_net, task_id, train_loader, memory,
            num_directions=config.grads_per_task,
            fisher=F_current,
            device=device,
        )
        logs = {
            "fopng_plus/fisher/min":             F_old.min().item(),
            "fopng_plus/fisher/max":             F_old.max().item(),
            "fopng_plus/fisher/mean":            F_old.mean().item(),
            "fopng_plus/memory/G_cols":          len(memory),
        }
        print(logs)
    # ─────────────────────────────────────────────────────────────────────
    # Final summary
    # ─────────────────────────────────────────────────────────────────────
    num_tasks = config.num_tasks
    print("\n" + "=" * 60)
    print("FINAL RESULTS  (test accuracy, %)")
    print("=" * 60)
    header = "       " + "  ".join(f"AfterT{t}" for t in range(num_tasks))
    print(header)
    for task_id in range(num_tasks):
        row = f"  T{task_id}  " + "  ".join(
            f"  {100*results[task_id][t]:5.1f}%" if t < len(results[task_id]) else "      -"
            for t in range(num_tasks)
        )
        print(row)

    final_accs = [results[t][-1] for t in range(num_tasks)]
    print(f"\n  Avg final accuracy : {100 * np.mean(final_accs):.2f}%")

    forgetting_vals = []
    for t in range(num_tasks - 1):
        best = max(results[t][:])        # peak accuracy while trained
        last = results[t][-1]            # accuracy after all tasks
        forgetting_vals.append(best - last)
    if forgetting_vals:
        print(f"  Avg forgetting     : {100 * np.mean(forgetting_vals):.2f}%")

    return results


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="FOPNG + HyperNetwork on Split CIFAR-10")

    # Training
    parser.add_argument("--seed",           type=int,   default=42)
    parser.add_argument("--device",         type=str,   default="auto")
    parser.add_argument("--batch_size",     type=int,   default=64)
    parser.add_argument("--epochs",         type=int,   default=10,
                        help="Epochs per task")
    parser.add_argument("--lr",             type=float, default=1e-3,
                        help="Shared-param learning rate (also Adam lr for task 0)")
    parser.add_argument("--task_emb_lr",    type=float, default=0.05)

    # FOPNG
    parser.add_argument("--grads_per_task", type=int,   default=150)
    parser.add_argument("--max_directions", type=int,   default=750)
    parser.add_argument("--lambda_reg",     type=float, default=1e-3)
    parser.add_argument("--fisher_weight",  type=float, default=0.5,
                        help="EMA weight for F_old update")
    parser.add_argument("--fisher_samples", type=int,   default=512,
                        help="Max samples for Fisher estimation (0 = full dataset)")

    # HyperNetwork
    parser.add_argument("--task_emb_dim",   type=int,   default=16)
    parser.add_argument("--chunk_size",     type=int,   default=256)
    parser.add_argument("--chunk_emb_dim",  type=int,   default=8)
    parser.add_argument("--hyper_hidden",   type=int,   default=64)

    args = parser.parse_args()

    cfg = Config(
        seed                   = args.seed,
        device                 = args.device,
        batch_size             = args.batch_size,
        epochs_per_task        = args.epochs,
        lr                     = args.lr,
        task_emb_lr            = args.task_emb_lr,
        grads_per_task         = args.grads_per_task,
        max_directions         = args.max_directions,
        fopng_lambda_reg       = args.lambda_reg,
        fopng_new_fisher_weight= args.fisher_weight,
        fisher_batch_size      = args.fisher_samples if args.fisher_samples > 0 else None,
        num_tasks              = 5,
        task_embedding_dim     = args.task_emb_dim,
        chunk_size             = args.chunk_size,
        chunk_embedding_dim    = args.chunk_emb_dim,
        hyper_hidden_dim       = args.hyper_hidden,
    )

    run_experiment(cfg)