"""
Split-CIFAR100 Task Generator
==============================
10 tasks, each a 10-class classification of consecutive classes:
  Task 0: Classes 0-9  ...  Task 9: Classes 90-99

Canonical hypernetwork setup — von Oswald et al. (2020), Appendix C:
  Target network  : ResNet-32 CIFAR (~468,540 params incl. BN weight/bias)
  Hypernetwork    : Linear(64 → 7000) — NO hidden layers, direct mapping
  chunk_size      : 7000
  emb_dim (task)  : 32
  emb_dim (chunk) : 32
  lr              : 0.001  (Adam, default PyTorch betas)
  batch_size      : 32
  max_epochs      : 200
  beta_reg        : 0.01

BatchNorm handling (von Oswald et al., Appendix C):
  - BN weight (gamma) and bias (beta) ARE trainable → generated by the hypernetwork.
  - BN running_mean / running_var are NOT parameters → NOT generated.
  - They must be checkpointed after each task and restored at evaluation.
  - Call model.save_bn_stats(task_id) after training each task.
  - Call model.load_bn_stats(task_id) before evaluating that task.

To use no hidden layers pass --hyper_hidden_dim 0 (or equivalent in your
HyperNetwork constructor so the MLP has no hidden layers, just Linear(64, 7000)).
"""
from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import DataLoader, Dataset
from torchvision import datasets, transforms
from types import SimpleNamespace
from typing import Dict, List, Optional, Tuple
from tqdm import tqdm


# ─────────────────────────────────────────────────────────────────────────────
# ResNet-32 CIFAR  (He et al., 2016 — CIFAR variant, BatchNorm)
# Hypernetwork target: BN gamma/beta generated, running stats checkpointed.
# ─────────────────────────────────────────────────────────────────────────────

class _BasicBlockBN(nn.Module):
    expansion = 1

    def __init__(self, in_planes: int, planes: int, stride: int = 1):
        super().__init__()
        self.conv1 = nn.Conv2d(in_planes, planes, 3,
                               stride=stride, padding=1, bias=False)
        self.bn1   = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, 3,
                               stride=1, padding=1, bias=False)
        self.bn2   = nn.BatchNorm2d(planes)

        self.shortcut = nn.Sequential()
        if stride != 1 or in_planes != planes:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_planes, planes, 1, stride=stride, bias=False),
                nn.BatchNorm2d(planes),
            )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out += self.shortcut(x)
        return F.relu(out)


class ResNet32CIFAR(nn.Module):
    """
    ResNet-32 for CIFAR following von Oswald et al. (2020).

    n = 5 blocks per stage → 1 + 3*(5*2) + 1 = 32 weight layers.
    Channels: 16 → 32 → 64.
    Global average pool → Linear(64, num_classes).

    BatchNorm gamma/beta are trainable parameters and ARE generated by the
    hypernetwork. BN running_mean/running_var are buffers and must be
    checkpointed manually using save_bn_stats / load_bn_stats.
    """
    N_BLOCKS = 5

    def __init__(self, num_classes: int = 10):
        super().__init__()
        self._in = 16

        self.conv1  = nn.Conv2d(3, 16, 3, stride=1, padding=1, bias=False)
        self.bn1    = nn.BatchNorm2d(16)
        self.layer1 = self._make_stage(16, stride=1)
        self.layer2 = self._make_stage(32, stride=2)
        self.layer3 = self._make_stage(64, stride=2)
        self.linear = nn.Linear(64, num_classes)

        # Per-task BN running-stat storage  {task_id -> {buf_name -> tensor}}
        self._bn_checkpoints: Dict[int, Dict[str, torch.Tensor]] = {}

        self._init_weights()

    def _make_stage(self, planes: int, stride: int) -> nn.Sequential:
        blocks = [_BasicBlockBN(self._in, planes, stride)]
        self._in = planes
        for _ in range(self.N_BLOCKS - 1):
            blocks.append(_BasicBlockBN(planes, planes, stride=1))
        return nn.Sequential(*blocks)

    def _init_weights(self) -> None:
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out",
                                        nonlinearity="relu")
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.layer1(out)
        out = self.layer2(out)
        out = self.layer3(out)
        out = F.avg_pool2d(out, out.size(3))
        out = out.view(out.size(0), -1)
        return self.linear(out)

    # ── BN running-stat checkpointing ─────────────────────────────────────
    def save_bn_stats(self, task_id: int) -> None:
        """
        Save running_mean / running_var for all BN layers after training
        task `task_id`. Must be called once per task immediately after the
        training loop ends, BEFORE loading any other task's weights.
        """
        tid = int(task_id)
        snapshot: Dict[str, torch.Tensor] = {}
        for name, buf in self.named_buffers():
            if "running_mean" in name or "running_var" in name:
                snapshot[name] = buf.detach().clone().cpu()
        self._bn_checkpoints[tid] = snapshot

    def load_bn_stats(self, task_id: int) -> None:
        """
        Restore running_mean / running_var for task `task_id` before
        evaluating that task. Requires save_bn_stats(task_id) was called.
        """
        tid = int(task_id)
        if tid not in self._bn_checkpoints:
            raise KeyError(
                f"No BN stats saved for task {tid}. "
                "Call save_bn_stats(task_id) after training that task."
            )
        for name, buf in self.named_buffers():
            if name in self._bn_checkpoints[tid]:
                buf.copy_(self._bn_checkpoints[tid][name])

    # ── Hypernetwork training loop interface ───────────────────────────────
    def spawn(self, task_id) -> None:
        """No-op — task is routed via task embedding, not an output head."""
        pass

    @property
    def _shared_params(self) -> List[nn.Parameter]:
        return list(self.parameters())

    @property
    def num_shared_params(self) -> int:
        return sum(p.numel() for p in self.parameters())


# ─────────────────────────────────────────────────────────────────────────────
# Multi-head standalone target  (projection-method / non-hypernetwork runs)
# Same ResNet-32 depth but GroupNorm: no running stats, no checkpointing needed.
# ─────────────────────────────────────────────────────────────────────────────

class _BasicBlockGN(nn.Module):
    expansion = 1

    def __init__(self, in_planes: int, planes: int,
                 stride: int = 1, num_groups: int = 16):
        super().__init__()
        self.conv1 = nn.Conv2d(in_planes, planes, 3,
                               stride=stride, padding=1, bias=False)
        self.gn1   = nn.GroupNorm(num_groups, planes)
        self.conv2 = nn.Conv2d(planes, planes, 3,
                               stride=1, padding=1, bias=False)
        self.gn2   = nn.GroupNorm(num_groups, planes)

        self.shortcut = nn.Sequential()
        if stride != 1 or in_planes != planes:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_planes, planes, 1, stride=stride, bias=False),
                nn.GroupNorm(num_groups, planes),
            )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out = F.relu(self.gn1(self.conv1(x)))
        out = self.gn2(self.conv2(out))
        out += self.shortcut(x)
        return F.relu(out)


class MultiHeadTargetCNN(nn.Module):
    """
    Multi-head ResNet-32 with GroupNorm for standalone projection experiments.
    GroupNorm has no running statistics so no per-task checkpointing is needed.
    """
    N_BLOCKS = 5

    def __init__(self, num_tasks: int, device,
                 num_classes_per_task: int = 10, num_groups: int = 16):
        super().__init__()
        self._in = 16

        self.conv1  = nn.Conv2d(3, 16, 3, stride=1, padding=1,
                                bias=False).to(device)
        self.gn1    = nn.GroupNorm(num_groups, 16).to(device)
        self.layer1 = self._make_stage(16, 1, num_groups, device)
        self.layer2 = self._make_stage(32, 2, num_groups, device)
        self.layer3 = self._make_stage(64, 2, num_groups, device)

        self.heads = nn.ModuleList([
            nn.Linear(64, num_classes_per_task) for _ in range(num_tasks)
        ]).to(device)

        self.register_buffer("_active_task_id",
                             torch.tensor(0, dtype=torch.long))

    def _make_stage(self, planes, stride, ng, device):
        blocks = [_BasicBlockGN(self._in, planes, stride, ng).to(device)]
        self._in = planes
        for _ in range(self.N_BLOCKS - 1):
            blocks.append(_BasicBlockGN(planes, planes, 1, ng).to(device))
        return nn.Sequential(*blocks)

    @property
    def _shared_params(self) -> List[nn.Parameter]:
        return (list(self.conv1.parameters()) +
                list(self.gn1.parameters()) +
                list(self.layer1.parameters()) +
                list(self.layer2.parameters()) +
                list(self.layer3.parameters()))

    @property
    def num_shared_params(self) -> int:
        return sum(p.numel() for p in self._shared_params)

    def spawn(self, task_id) -> None:
        if torch.is_tensor(task_id):
            self._active_task_id.fill_(task_id.item())
        else:
            self._active_task_id.fill_(task_id)

    def update_task_specific_params(self, lr: float) -> None:
        with torch.no_grad():
            for p in self.heads[self._active_task_id.item()].parameters():
                if p.grad is not None:
                    p.data.add_(-lr * p.grad)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out = F.relu(self.gn1(self.conv1(x)))
        out = self.layer1(out)
        out = self.layer2(out)
        out = self.layer3(out)
        out = F.avg_pool2d(out, out.size(3))
        out = out.view(out.size(0), -1)
        return self.heads[self._active_task_id.item()](out)


# ─────────────────────────────────────────────────────────────────────────────
# Dataset helper
# ─────────────────────────────────────────────────────────────────────────────

class RemappedSubset(Dataset):
    """Filters dataset to allowed_classes and remaps labels to 0…k-1."""

    def __init__(self, base_dataset, allowed_classes: List[int],
                 indices: Optional[List[int]] = None):
        self.base = base_dataset
        self.class_to_new = {c: i for i, c in enumerate(sorted(allowed_classes))}
        if indices is not None:
            self.indices = indices
        else:
            allowed_set = set(allowed_classes)
            targets = getattr(base_dataset, "targets", None)
            if targets is not None:
                self.indices = [i for i, lbl in enumerate(targets)
                                if int(lbl) in allowed_set]
            else:
                self.indices = [i for i, (_, lbl) in enumerate(base_dataset)
                                if int(lbl) in allowed_set]

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, idx: int):
        img, lbl = self.base[self.indices[idx]]
        return img, self.class_to_new[int(lbl)]


# ─────────────────────────────────────────────────────────────────────────────
# Task Generator
# ─────────────────────────────────────────────────────────────────────────────

class TaskGenerator:
    TASK_CLASSES = [list(range(i, i + 10)) for i in range(0, 100, 10)]

    config = SimpleNamespace(
        input_dim       = 3072,
        num_classes     = 10,
        num_tasks       = 10,
        criterion       = nn.CrossEntropyLoss(),
        task_classes    = TASK_CLASSES,
        grads_per_task  = 150,
        max_directions  = 750,
    )

    # Hypernetwork target — ResNet-32 with BatchNorm (canonical)
    target_network = ResNet32CIFAR(num_classes=10)

    # Standalone projection target — ResNet-32 depth with GroupNorm
    solo_target = MultiHeadTargetCNN

    _train_data: Optional[datasets.CIFAR100] = None
    _test_data:  Optional[datasets.CIFAR100] = None

    @classmethod
    def _load(cls) -> None:
        if cls._train_data is not None:
            return
        print(" [TaskGenerator] Initializing base CIFAR-100 datasets...")
        tf_train = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(32, padding=4),
            transforms.ToTensor(),
            transforms.Normalize((0.5071, 0.4867, 0.4408),
                                  (0.2675, 0.2565, 0.2761)),
        ])
        tf_test = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.5071, 0.4867, 0.4408),
                                  (0.2675, 0.2565, 0.2761)),
        ])
        cls._train_data = datasets.CIFAR100(
            root="./data", train=True,  download=True, transform=tf_train)
        cls._test_data  = datasets.CIFAR100(
            root="./data", train=False, download=True, transform=tf_test)

    @classmethod
    def _make_split(cls, dataset, allowed_classes: List[int],
                    batch_size: int = 32, shuffle: bool = True,
                    desc: str = "Processing Task") -> DataLoader:
        allowed_set = set(allowed_classes)
        indices = [i for i, lbl in
                   enumerate(tqdm(dataset.targets,
                                  desc=f"  {desc}", leave=False))
                   if lbl in allowed_set]
        return DataLoader(
            RemappedSubset(dataset, allowed_classes, indices),
            batch_size=batch_size, shuffle=shuffle,
            num_workers=2, pin_memory=True,
        )

    @classmethod
    def generate(cls, task_id: int,
                 batch_size: int = 32) -> Tuple[DataLoader, DataLoader]:
        assert 0 <= task_id < cls.config.num_tasks, \
            f"task_id must be in [0, {cls.config.num_tasks}), got {task_id}"
        cls._load()
        allowed = cls.TASK_CLASSES[task_id]
        prefix  = f"Task {task_id + 1} (classes {allowed[0]}-{allowed[-1]})"
        return (
            cls._make_split(cls._train_data, allowed,
                            batch_size=batch_size, shuffle=True,
                            desc=f"{prefix} Train"),
            cls._make_split(cls._test_data,  allowed,
                            batch_size=batch_size, shuffle=False,
                            desc=f"{prefix} Test"),
        )