"""
Split-CIFAR100 Task Generator
==============================
10 tasks, each a 10-class classification of consecutive classes:
  Task 0: Classes 0-9  ...  Task 9: Classes 90-99

Canonical hypernetwork setup — von Oswald et al. (2020), Appendix C:
  Target network  : ResNet-32 CIFAR (~468,540 params incl. BN weight/bias)
  Hypernetwork    : Linear(64 → 7000) — NO hidden layers, direct mapping
  chunk_size      : 7000
  emb_dim (task)  : 32
  emb_dim (chunk) : 32
  lr              : 0.001  (Adam, default PyTorch betas)
  batch_size      : 32
  max_epochs      : 200
  beta_reg        : 0.01

BatchNorm handling (von Oswald et al., Appendix C):
  - BN weight (gamma) and bias (beta) ARE trainable → generated by the hypernetwork.
  - BN running_mean / running_var are NOT parameters → NOT generated.
  - They must be checkpointed after each task and restored at evaluation.
  - Call model.save_bn_stats(task_id) after training each task.
  - Call model.load_bn_stats(task_id) before evaluating that task.

To use no hidden layers pass --hyper_hidden_dim 0 (or equivalent in your
HyperNetwork constructor so the MLP has no hidden layers, just Linear(64, 7000)).
"""
from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import DataLoader, Dataset
from torchvision import datasets, transforms
from types import SimpleNamespace
from typing import Dict, List, Optional, Tuple
from tqdm import tqdm
from models.cnn import SimpleCIFARCNN, MultiHeadCIFARCNN
from utils import RemappedSubset

# ─────────────────────────────────────────────────────────────────────────────
# Task Generator
# ─────────────────────────────────────────────────────────────────────────────

class TaskGenerator:
    TASK_CLASSES = [list(range(i, i + 10)) for i in range(0, 100, 10)]

    config = SimpleNamespace(
        input_dim       = 3072,
        num_classes     = 10,
        num_tasks       = 10,
        criterion       = nn.CrossEntropyLoss(),
        task_classes    = TASK_CLASSES,
        grads_per_task  = 150,
        max_directions  = 750,
    )

    # Hypernetwork target — ResNet-32 with BatchNorm (canonical)
    target_network = SimpleCIFARCNN

    # Standalone projection target — ResNet-32 depth with GroupNorm
    solo_target = MultiHeadCIFARCNN

    _train_data: Optional[datasets.CIFAR100] = None
    _test_data:  Optional[datasets.CIFAR100] = None

    @classmethod
    def _load(cls) -> None:
        if cls._train_data is not None:
            return
        print(" [TaskGenerator] Initializing base CIFAR-100 datasets...")
        tf_train = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.5071, 0.4867, 0.4408),
                                  (0.2675, 0.2565, 0.2761)),
        ])
        tf_test = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.5071, 0.4867, 0.4408),
                                  (0.2675, 0.2565, 0.2761)),
        ])
        cls._train_data = datasets.CIFAR100(
            root="./data", train=True,  download=True, transform=tf_train)
        cls._test_data  = datasets.CIFAR100(
            root="./data", train=False, download=True, transform=tf_test)

    @classmethod
    def _make_split(cls, dataset, allowed_classes: List[int],
                    batch_size: int = 32, shuffle: bool = True,
                    desc: str = "Processing Task") -> DataLoader:
        allowed_set = set(allowed_classes)
        indices = [i for i, lbl in
                   enumerate(tqdm(dataset.targets,
                                  desc=f"  {desc}", leave=False))
                   if lbl in allowed_set]
        return DataLoader(
            RemappedSubset(dataset, allowed_classes, indices),
            batch_size=batch_size, shuffle=shuffle,
            num_workers=2, pin_memory=True,
        )

    @classmethod
    def generate(cls, task_id: int,
                 batch_size: int = 32) -> Tuple[DataLoader, DataLoader]:
        assert 0 <= task_id < cls.config.num_tasks, \
            f"task_id must be in [0, {cls.config.num_tasks}), got {task_id}"
        cls._load()
        allowed = cls.TASK_CLASSES[task_id]
        prefix  = f"Task {task_id + 1} (classes {allowed[0]}-{allowed[-1]})"
        return (
            cls._make_split(cls._train_data, allowed,
                            batch_size=batch_size, shuffle=True,
                            desc=f"{prefix} Train"),
            cls._make_split(cls._test_data,  allowed,
                            batch_size=batch_size, shuffle=False,
                            desc=f"{prefix} Test"),
        )