"""
Split-CIFAR100 Task Generator
==============================
10 tasks, each a 10-class classification of consecutive classes:
  Task 0: Classes 0-9  ...  Task 9: Classes 90-99

Canonical hypernetwork setup — von Oswald et al. (2020), Appendix C:
  Target network  : ResNet-32 CIFAR (~468,540 params incl. BN weight/bias)
  Hypernetwork    : Linear(64 → 7000) — NO hidden layers, direct mapping
  chunk_size      : 7000
  emb_dim (task)  : 32
  emb_dim (chunk) : 32
  lr              : 0.001  (Adam, default PyTorch betas)
  batch_size      : 32
  max_epochs      : 200
  beta_reg        : 0.01

BatchNorm handling (von Oswald et al., Appendix C):
  - BN weight (gamma) and bias (beta) ARE trainable → generated by the hypernetwork.
  - BN running_mean / running_var are NOT parameters → NOT generated.
  - They must be checkpointed after each task and restored at evaluation.
  - Call model.save_bn_stats(task_id) after training each task.
  - Call model.load_bn_stats(task_id) before evaluating that task.

To use no hidden layers pass --hyper_hidden_dim 0 (or equivalent in your
HyperNetwork constructor so the MLP has no hidden layers, just Linear(64, 7000)).
"""
from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import DataLoader, Dataset
from torchvision import datasets, transforms
from types import SimpleNamespace
from typing import Dict, List, Optional, Tuple
from tqdm import tqdm



class MultiHeadCNN(nn.Module):
    """
    FOPNG-canonical CNN for Split-CIFAR10 / Split-CIFAR100.
    Shared backbone (4 conv layers + 2 FC layers); task-specific output heads.
    Backbone parameters are protected by the projection optimizer.
    """

    def __init__(self, num_tasks: int, device,
                 num_classes_per_task: int = 10):   # 2 for CIFAR-10, 10 for CIFAR-100
        super().__init__()

        # ── Shared backbone ──────────────────────────────────────────────────
        # Block 1: Conv-ReLU-Conv-ReLU-MaxPool   3 → 32 channels
        self.conv1 = nn.Conv2d(3,  32, kernel_size=3, padding=1).to(device)
        self.conv2 = nn.Conv2d(32, 32, kernel_size=3, padding=1).to(device)
        # Block 2: Conv-ReLU-Conv-ReLU-MaxPool  32 → 64 channels
        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, padding=1).to(device)
        self.conv4 = nn.Conv2d(64, 64, kernel_size=3, padding=1).to(device)

        # FC layers with dropout
        self.fc1     = nn.Linear(64 * 8 * 8, 256).to(device)   # 4096 → 256
        self.fc2     = nn.Linear(256, 256).to(device)            # 256  → 256
        self.dropout = nn.Dropout(p=0.5)

        # ── Task-specific heads ───────────────────────────────────────────────
        self.heads = nn.ModuleList([
            nn.Linear(256, num_classes_per_task) for _ in range(num_tasks)
        ]).to(device)

        self.register_buffer("_active_task_id", torch.tensor(0, dtype=torch.long))

    # ── Projection optimizer interface ───────────────────────────────────────
    @property
    def _shared_params(self) -> List[nn.Parameter]:
        """Backbone only — heads are task-specific and excluded from projection."""
        return (list(self.conv1.parameters()) +
                list(self.conv2.parameters()) +
                list(self.conv3.parameters()) +
                list(self.conv4.parameters()) +
                list(self.fc1.parameters()) +
                list(self.fc2.parameters()))

    @property
    def num_shared_params(self) -> int:
        return sum(p.numel() for p in self._shared_params)

    def spawn(self, task_id) -> None:
        if torch.is_tensor(task_id):
            self._active_task_id.fill_(task_id.item())
        else:
            self._active_task_id.fill_(task_id)

    # ── Forward ───────────────────────────────────────────────────────────────
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Block 1
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2)          # 32×32 → 16×16
        # Block 2
        x = F.relu(self.conv3(x))
        x = F.relu(self.conv4(x))
        x = F.max_pool2d(x, 2)          # 16×16 → 8×8
        # FC
        x = x.view(x.size(0), -1)       # 64×8×8 = 4096
        x = self.dropout(F.relu(self.fc1(x)))
        x = self.dropout(F.relu(self.fc2(x)))
        return self.heads[self._active_task_id.item()](x)


# ─────────────────────────────────────────────────────────────────────────────
# Dataset helper
# ─────────────────────────────────────────────────────────────────────────────

class RemappedSubset(Dataset):
    """Filters dataset to allowed_classes and remaps labels to 0…k-1."""

    def __init__(self, base_dataset, allowed_classes: List[int],
                 indices: Optional[List[int]] = None):
        self.base = base_dataset
        self.class_to_new = {c: i for i, c in enumerate(sorted(allowed_classes))}
        if indices is not None:
            self.indices = indices
        else:
            allowed_set = set(allowed_classes)
            targets = getattr(base_dataset, "targets", None)
            if targets is not None:
                self.indices = [i for i, lbl in enumerate(targets)
                                if int(lbl) in allowed_set]
            else:
                self.indices = [i for i, (_, lbl) in enumerate(base_dataset)
                                if int(lbl) in allowed_set]

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, idx: int):
        img, lbl = self.base[self.indices[idx]]
        return img, self.class_to_new[int(lbl)]


# ─────────────────────────────────────────────────────────────────────────────
# Task Generator
# ─────────────────────────────────────────────────────────────────────────────

class TaskGenerator:
    TASK_CLASSES = [list(range(i, i + 10)) for i in range(0, 100, 10)]

    config = SimpleNamespace(
        input_dim       = 3072,
        num_classes     = 10,
        num_tasks       = 10,
        criterion       = nn.CrossEntropyLoss(),
        task_classes    = TASK_CLASSES,
        grads_per_task  = 150,
        max_directions  = 750,
    )

    # Hypernetwork target — ResNet-32 with BatchNorm (canonical)
    target_network = None

    # Standalone projection target — ResNet-32 depth with GroupNorm
    solo_target = MultiHeadCNN

    _train_data: Optional[datasets.CIFAR100] = None
    _test_data:  Optional[datasets.CIFAR100] = None

    @classmethod
    def _load(cls) -> None:
        if cls._train_data is not None:
            return
        print(" [TaskGenerator] Initializing base CIFAR-100 datasets...")
        tf_train = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.5071, 0.4867, 0.4408),
                                  (0.2675, 0.2565, 0.2761)),
        ])
        tf_test = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.5071, 0.4867, 0.4408),
                                  (0.2675, 0.2565, 0.2761)),
        ])
        cls._train_data = datasets.CIFAR100(
            root="./data", train=True,  download=True, transform=tf_train)
        cls._test_data  = datasets.CIFAR100(
            root="./data", train=False, download=True, transform=tf_test)

    @classmethod
    def _make_split(cls, dataset, allowed_classes: List[int],
                    batch_size: int = 32, shuffle: bool = True,
                    desc: str = "Processing Task") -> DataLoader:
        allowed_set = set(allowed_classes)
        indices = [i for i, lbl in
                   enumerate(tqdm(dataset.targets,
                                  desc=f"  {desc}", leave=False))
                   if lbl in allowed_set]
        return DataLoader(
            RemappedSubset(dataset, allowed_classes, indices),
            batch_size=batch_size, shuffle=shuffle,
            num_workers=2, pin_memory=True,
        )

    @classmethod
    def generate(cls, task_id: int,
                 batch_size: int = 32) -> Tuple[DataLoader, DataLoader]:
        assert 0 <= task_id < cls.config.num_tasks, \
            f"task_id must be in [0, {cls.config.num_tasks}), got {task_id}"
        cls._load()
        allowed = cls.TASK_CLASSES[task_id]
        prefix  = f"Task {task_id + 1} (classes {allowed[0]}-{allowed[-1]})"
        return (
            cls._make_split(cls._train_data, allowed,
                            batch_size=batch_size, shuffle=True,
                            desc=f"{prefix} Train"),
            cls._make_split(cls._test_data,  allowed,
                            batch_size=batch_size, shuffle=False,
                            desc=f"{prefix} Test"),
        )