_wandb:
    value:
        cli_version: 0.25.0
        e:
            phg4ob00sfmc88brvm664bd3vzcb0my1:
                args:
                    - --task
                    - split_mnist
                    - --alpha=0.5
                    - --lam=1e-8
                    - --methods
                    - fopng
                    - --hyper_hidden_dim=30
                    - --chunk_embedding_dim=15
                    - --task_embedding_dim=15
                    - --epochs=7
                    - --lr=1e-4
                    - --fisher_samples=4096
                    - --grads_per_task=300
                    - --max_directions=1200
                codePath: HyperFisher/main.py
                codePathLocal: main.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "427605082112"
                        used: "362286481408"
                email: michalowski.jb@gmail.com
                executable: /home/kelares/Desktop/thesis/venv_f_h/bin/python
                git:
                    commit: 4466096ff53422c1c935a30a1b226ce3e576c7f9
                    remote: https://github.com/Kelares/HyperFisher
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-fe4c318c-118b-9415-a588-d3deb521d1b8
                host: PAM
                memory:
                    total: "41723392000"
                os: Linux-6.19.9-arch1-1-x86_64-with-glibc2.43
                program: /home/kelares/Desktop/HyperFisher/HyperFisher/main.py
                python: CPython 3.10.19
                root: /home/kelares/Desktop/HyperFisher/HyperFisher
                startedAt: "2026-03-28T21:06:52.230071Z"
                writerId: phg4ob00sfmc88brvm664bd3vzcb0my1
        m:
            - "1": task_completed
              "6":
                - 3
              "7": []
            - "2": fopng/eval/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 7
                - 16
            "4": 3.10.19
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
alpha:
    value: 0.5
check_vram:
    value: false
chunk_embedding_dim:
    value: 15
chunk_size:
    value: 1000
epochs:
    value: 7
fisher_samples:
    value: 4096
grads_per_task:
    value: 300
hyper_hidden_dim:
    value: 30
lam:
    value: 1e-08
lr:
    value: 0.0001
max_directions:
    value: 1200
methods:
    value:
        - fopng
model:
    value: HyperNetwork
num_tasks:
    value: 5
seed:
    value: 1234
task:
    value: split_mnist
task_embedding_dim:
    value: 15
