_wandb:
    value:
        cli_version: 0.25.0
        e:
            sjf6s35d96idmf5gst9l2sa0d04rukyt:
                args:
                    - --task=split_cifar10
                    - --chunk_size=50000
                    - --lam=5e-4
                    - --alpha=0.5
                    - --grads_per_task=100
                    - --max_direction=300
                    - --hyper_hidden_dim=100
                    - --methods
                    - fopng
                    - --task_embedding_dim=15
                    - --chunk_embedding_dim=15
                    - --epochs=15
                    - --lr=1e-4
                codePath: HyperFisher/main.py
                codePathLocal: main.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "427605082112"
                        used: "362717855744"
                email: michalowski.jb@gmail.com
                executable: /home/kelares/Desktop/thesis/venv_f_h/bin/python
                git:
                    commit: a7543277e18952e45e1fd55313cffbc3d0dcd859
                    remote: https://github.com/Kelares/HyperFisher
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-fe4c318c-118b-9415-a588-d3deb521d1b8
                host: PAM
                memory:
                    total: "41723379712"
                os: Linux-6.19.9-arch1-1-x86_64-with-glibc2.43
                program: /home/kelares/Desktop/HyperFisher/HyperFisher/main.py
                python: CPython 3.10.19
                root: /home/kelares/Desktop/HyperFisher/HyperFisher
                startedAt: "2026-03-29T00:17:03.443257Z"
                writerId: sjf6s35d96idmf5gst9l2sa0d04rukyt
        m:
            - "1": task_completed
              "6":
                - 3
              "7": []
            - "2": fopng/eval/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 7
                - 16
            "4": 3.10.19
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
alpha:
    value: 0.5
architecture:
    value: |-
        HyperNetwork(
          (target_network): CIFARTarget(
            (convs): Sequential(
              (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (3): ReLU()
              (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
              (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (6): ReLU()
              (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
            )
            (fc): Sequential(
              (0): Linear(in_features=8192, out_features=64, bias=True)
              (1): ReLU()
              (2): Linear(in_features=64, out_features=10, bias=True)
            )
          )
          (chunk_emb): Embedding(13, 15)
          (task_emb): Embedding(5, 15)
          (layers): Sequential(
            (0): Linear(in_features=30, out_features=100, bias=True)
            (1): ReLU()
            (2): Linear(in_features=100, out_features=50000, bias=True)
          )
        )
check_vram:
    value: false
chunk_embedding_dim:
    value: 15
chunk_size:
    value: 50000
epochs:
    value: 15
fisher_samples:
    value: 1024
grads_per_task:
    value: 100
hyper_hidden_dim:
    value: 100
lam:
    value: 0.0005
lr:
    value: 0.0001
max_directions:
    value: 300
methods:
    value:
        - fopng
model:
    value: HyperNetwork
num_of_chunks:
    value: 13
num_tasks:
    value: 5
seed:
    value: 1234
task:
    value: split_cifar10
task_embedding_dim:
    value: 15
